### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by yar3333** [drdk/dr-font-support#2]
```shell
c:\3\dr-font-support-master>npm install
npm WARN deprecated jDataView@2.2.5: According to new npm naming restrictions, jDataView was renamed to jdataview in registry and this package is left only for backward compatibility.
dr-font-support@0.3.6 c:\3\dr-font-support-master
+-- async@0.9.2
+-- clean-css@1.1.7
| `-- commander@2.0.0
+-- dr-webfont-inliner@0.4.1
| +-- async@0.9.2  deduped
| `-- optimist@0.6.1
|   +-- minimist@0.0.10
|   `-- wordwrap@0.0.3
+-- nodettfpatch@1.0.2
+-- svg2ttf@1.0.7
| +-- argparse@0.1.16
| | +-- underscore@1.7.0
| | `-- underscore.string@2.4.0
| +-- jDataView@2.2.5
| +-- lodash@1.3.1
| `-- xmldom@0.1.27
+-- ttf2eot@1.2.0
| `-- argparse@0.1.16  deduped
`-- ttf2woff@1.1.0
  +-- argparse@0.1.16  deduped
  `-- jDataView@2.2.5  deduped

npm WARN dr-font-support@0.3.6 No repository field.
npm WARN dr-font-support@0.3.6 license should be a valid SPDX license expression

c:\3\dr-font-support-master>node build.js
c:\3\dr-font-support-master\node_modules\jDataView\src\jDataView.js:259
                        throw new TypeError('Size is not a number.');
                        ^

TypeError: Size is not a number.
    at Object._checkBounds (c:\3\dr-font-support-master\node_modules\jDataView\src\jDataView.js:259:10)
    at Object._setBytes (c:\3\dr-font-support-master\node_modules\jDataView\src\jDataView.js:358:8)
    at Object.setBytes (c:\3\dr-font-support-master\node_modules\jDataView\src\jDataView.js:383:8)
    at Object.writeBytes (c:\3\dr-font-support-master\node_modules\jDataView\src\jDataView.js:387:8)
    at c:\3\dr-font-support-master\node_modules\ttf2woff\index.js:271:18
    at Deflate.onEnd (zlib.js:227:5)
    at emitNone (events.js:91:20)
    at Deflate.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
```

**Comment by phloe** [comment]
FWIW - devdependencies are fixed now :)
